// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIfObn92VFBTnWSAKawEbGqA6dMkPXHmQ',
    appId: '1:946439129619:android:a5efedbcb978d9ed93cde6',
    messagingSenderId: '946439129619',
    projectId: 'cs-project-7200e',
    databaseURL: 'https://cs-project-7200e-default-rtdb.firebaseio.com',
    storageBucket: 'cs-project-7200e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuTOYcbBhPZEzF9_gDIuZSGNNOaB-As4s',
    appId: '1:946439129619:ios:69badb2300ceb6e293cde6',
    messagingSenderId: '946439129619',
    projectId: 'cs-project-7200e',
    databaseURL: 'https://cs-project-7200e-default-rtdb.firebaseio.com',
    storageBucket: 'cs-project-7200e.appspot.com',
    iosClientId: '946439129619-nekd8keatnk020npupafhq4esa040vl0.apps.googleusercontent.com',
    iosBundleId: 'com.example.eTransaction',
  );
}
