// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdT2CwM5wcXkRhllS3OCdM6IOzSmLBQJ4',
    appId: '1:6380183656:android:c3f96be4fb577cf231dbdd',
    messagingSenderId: '6380183656',
    projectId: 'e-transactions-346',
    databaseURL: 'https://e-transactions-346-default-rtdb.firebaseio.com',
    storageBucket: 'e-transactions-346.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiE9-nJibafo8Uc8vMWnmWTmw7GXFWiTg',
    appId: '1:6380183656:ios:9b0f9d076179ce8531dbdd',
    messagingSenderId: '6380183656',
    projectId: 'e-transactions-346',
    databaseURL: 'https://e-transactions-346-default-rtdb.firebaseio.com',
    storageBucket: 'e-transactions-346.appspot.com',
    iosClientId: '6380183656-cojt07r4kvvu1qga6uqr4p5oh1p7qphp.apps.googleusercontent.com',
    iosBundleId: 'com.eTransact.app',
  );
}
